# kick: 1

version: 2.1

commands:
  run_tests:
    description: "Build @astronautlabs/scte35 and run the test suite"
    parameters:
      version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
          - v1-dependencies-<< parameters.version >>-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-<< parameters.version >>-{{ checksum "package.json" }}
      - run: npm test
      - run: npm test # perhaps this will fix coverage reporting?
      - run: npm run benchmark
      - store_artifacts:
          path: coverage
jobs:
  node-15:
    docker:
      - image: circleci/node:15
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "15"
  node-14:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "14"
  node-12:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - run_tests:
          version: "12"

workflows:
  version: 2
  build:
    jobs:
      - node-15
      - node-14
      - node-12
